#!/bin/bash
# This goal of this script is to show how to use the files generated by rule `doe_config`.

set -eu -o pipefail

# The relative paths of the files are given as command line arguments thanks to the `$(locations ...)` function in the BUILD file.
FILES=("$@")

for f in "${FILES[@]}"
do
    echo "---"
    echo "Path: $f"
    echo "Content: $(cat "$f")"
done
