FROM {{cookiecutter.project_namespace}}/{{cookiecutter.project_slug}}:base
USER root

# Install extra dependencies here

# Update working directory
WORKDIR /{{cookiecutter.project_workdir}}
USER {{cookiecutter.project_user}}
