# Compiler options
SCALA_OPTS = [
    "-Ypartial-unification",
    "-unchecked",
    "-feature",
    "-language:reflectiveCalls",
]

# Export rules
def py_vars(name, variables={}, visibility=None):
    native.genrule(
        name = "{}_py".format(name),
        srcs = [],
        outs = ["{}.py".format(name)],
        cmd = "echo '# generated by py_vars' > $@;" + ";".join([
            """sed -i '$$a%s = %s' $@""" % (k, v)
            for k, v in variables.items()
        ])
    )
    native.py_library(
        name = name,
        srcs = ["{}.py".format(name)],
        visibility = visibility,
    )
